#!/usr/bin/env bash
set -euo pipefail

case "$(uname -s)" in
  Darwin)
    echo "mac"
    ;;
  Linux)
    if [[ -f /etc/arch-release ]]; then
      echo "arch"
    else
      echo "linux"
    fi
    ;;
  *)
    echo "unknown"
    ;;
esac
